libs/zod-openapi/src/lib/zod-openapi.spec.ts
libs/zod-openapi/src/lib/zod-openapi.ts

Source: https://swagger.io/docs/specification/data-models/data-types/#pattern
Noticed in my testing that `zod-openapi` treats `z.string().regex(...)` as a string type with a `regex` property that is the regex itself, however according to the OpenAPI spec, this is actually incorrect and should follow what JSON Schema does, which is a `pattern` property that contains the source pattern for the regex.
This corrects it by changing that `regex` property to match the spec. It could be considered a breaking change I suppose (due to the removal of a field), but its making the library like up with OAPI more so more of a fix IMO.

[zod-openapi] change `regex` to `pattern` to match OpenAPI spec

---

libs/zod-nestjs/src/lib/http-errors.ts
libs/zod-nestjs/src/lib/zod-validation-pipe.ts

Update the behavior of the ZodValidationPipe when an invalid request is found to more closely match the default NestJS ValidationPipe.
As in the default NestJS ValidationPipe:
- The default http response status code is 400 Bad Request instead of 422 Unprocessable Entity.
- The http response status code can be customized using the same "errorHttpStatusCode" option.
- The message field in the response body is an array rather than a string, making it easier to read.

ZodValidationPipe: Update error handling to more closely match the default NestJS ValidationPipe

---

libs/zod-nestjs/src/lib/create-zod-dto.spec.ts
libs/zod-nestjs/src/lib/create-zod-dto.ts
libs/zod-nestjs/src/lib/zod-validation-pipe.ts

The static zodSchema field on the DTO classes now maintains the schema
type that is passed in, which allows it to be used to construct other
schemas. Previously this zodSchema field had type "CompatibleZodType"
rather than "T extends CompatibleZodType" which meant that most of the
type information was lost.
Workarounds:
Although not as concise, the schema value can be exported separately or
the zodSchema field can be redefined on each DTO class that needs it.
Breaking change:
The "T" in ZodDtoStatic<T> has changed from the output type to the
schema type. Code that is using the ZodDtoStatic type directly may need
to be updated. No changes are needed if just using the DTOs.
Examples:
```TypeScript
// user.dto.ts
import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod'; …
```

zod-nestjs: Allow using the zodSchema field to construct other types

---

.eslintrc.json
libs/zod-mock/package.json
libs/zod-mock/src/lib/zod-mock.ts

- Removing console.log because it ends up generating logs in some application that consumes it;
- Adding Eslint rule to avoid this problem;

Removing console.log and adding eslint rule

---

.vscode/settings.json
libs/zod-mock/package.json
libs/zod-mock/src/lib/zod-mock.spec.ts
libs/zod-mock/src/lib/zod-mock.ts

While using this library I encountered an error that would not allow me to continue using it. My schema has a field called 'phone_number'. The name is dictated by a third party and I cannot change it. Faker has a property at `faker.definitions.phone_number` which is not a function. This property was being found and this library was attempting to call it which threw an error.
This PR fixes this issue by verifying that the Faker function name which is returned by the `findMatchingFaker` function adheres to the `fakerFunction` type.
Additionally:
- searches for faker functions against `keyName` values after removing underscores and dashes. This allows key names such as 'phone_number' to utilize the most correct Faker function of `phoneNumber`
- adds unit test to verify functionality of …

Updates the findMatchingFaker function to guarantee that the Faker function is of type fakerFunction

---

libs/zod-openapi/src/lib/zod-openapi.spec.ts
libs/zod-openapi/src/lib/zod-openapi.ts

This PR adds a change to `extendApi` to merge the specified metadata into the existing `metaOpenApi` object, if it already exists. The motivation here is when extending a schema's openapi metadata more than once, the original information gets overwritten. 
Here's an example: 
```ts
const DateTimeSchema = extendApi(z.string(), { format: 'date-time', description: 'An ISO-8601 timestamp.' })
```
Later, you may want to reuse `DateTimeSchema`, but just override the description, keeping the `format`:
```ts
const CreatedAtSchema = extendApi(DateTimeSchema, { description: 'The creation date.' }). 
```
However, `extendApi` currently overwrites whatever is in `schema.metaOpenApi`, so that `CreatedAtSchema` does not have `format: 'date-time'` anymore. 
This PR merges it, which IMO is clearer since …

feat(zod-openapi): merge openapi metadata

---

libs/zod-openapi/src/lib/zod-openapi.spec.ts
libs/zod-openapi/src/lib/zod-openapi.ts

When parsing a record with an unknown value type, e.g:
```ts
const recordSchema = extendApi(z.record(z.unknown()), { 
description: 'A record with unknown value types.' 
});
```
Which is equivalent to the commonly used typescript type `Record<string, unknown>`.
when passed through generateSchema, it comes back with the following invalid JSON schema:
```js
{
type: 'object',
additionalProperties: { nullable: true },
description: 'A record with unknown value types.' 
}
```
ajv v8 comes back with the following error:
```
Error message: "\"nullable\" cannot be used without \"type\""
```
I think `ZodUnknown`, when passed through to generateSchema, will come back with `{ nullable: true }`, which perhaps is desirable in other situations, just not in a `record`. This PR explicitly checks for …

fix(zod-openapi): support unknown record value types

---

libs/zod-nestjs/README.md

Replaced https://github.com/anatine/zod-plugins/tree/main/packages/zod-openapi with https://github.com/anatine/zod-plugins/tree/main/libs/zod-openapi

Updated zod-openapi URL

---

libs/zod-mock/src/lib/zod-mock.spec.ts
libs/zod-mock/src/lib/zod-mock.ts

1. z.record  will cause TypeError: Cannot convert undefined or null to object
so I add a parseRecord to handle ZodRecord。
2. In addition to this，this pr fixes `[Error]: Max 2 should be greater than min 5.` error in spec.ts。
3. fix .nativeEnum mock data was undefined error

fix: record type and swap string min when greater than max

---

packages/zod-mock/src/lib/zod-mock.ts

Fix to native enum parsing when using string enums

Fix: nativeEnum parsing

---

packages/zod-mock/src/lib/zod-mock.ts

It is no longer necesary to divide by 2 the length of the enum object keys, as string enum do not have double binding ( { 0: "SOMETHING", SOMETHING: 0}).

fix: nativeEnum random pick function bias

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

I took the liberty to implement most of the missing type generators here. The only other ones I know are missing are `ZodUnknown` and `ZodAny`, but since there are a few ways to address that I didn't include any changes to those types in this PR.
The new handlers I added here are for:
- `ZodIntersection`
- `ZodTuple`
- `ZodFunction`
- `ZodDefault`
- `ZodPromise`
- `ZodLazy`
- `ZodBranded`
- `ZodNull`
- `ZodNaN`

zod-mock: Add missing type generators

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

`zod-mock` already uses faker to make random array selections in some places, but I noticed it was using `Math.random()` for newer features, which isn’t seedable. This PR replicates the style of other parts of the codebase to randomly select union & enum members.
As a bonus, I also used `randexp`’s preferred method to replace their internal RNG (which is to just override the `randInt` method) with a seeded one. With this, as far as I can tell, all RNG functionality is seedable!
There’s a bug that concerns me about the way randomness is seeded in this library, however. Resetting the seed on every generation makes certain combinations impossible to achieve. Because `faker.mersenne` will return the same values after being reset, we end up selecting elements in the same regions of arrays. For …

feat(zod-mock): Make union (incl. discriminated), enum (incl. native), and regex generation deterministic

---

packages/zod-nestjs/project.json

In October a couple commits were made that modified the nx project file for `zod-nestjs`.
(https://github.com/anatine/zod-plugins/commit/8e0e798943e541bfe0dcf6daafb299656a317738)
(https://github.com/anatine/zod-plugins/commit/6f20f44272fa2d8531b7b530695f537d0b2e6ed8)
It seems that may have caused this package to stop being published.
```
❯ npm view @anatine/zod-nestjs time
{
'1.8.0': '2022-10-05T18:44:43.639Z'
}
```
This commit just changes this project file to match the one in `zod-openapi`, as that is still publishing.

fix(zod-nestjs): set up nx project the same as zod-openapi

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

There were a final handful of sources of non-seedable randomness in the package (in `string`, `boolean`, and `date`), which I’ve implemented in this PR. I also re-enabled and expanded the test for a customer faker instance.
This has the overall benefit of allowing fully deterministic generation, subject to 2 caveats (that I can tell). For `z.date()`, the library uses `faker.date.soon()` to generate dates, and for `z.string()` fields named `date` or `dateTime`, the library uses `faker.date.recent()` to generate an ISO string. These are reasonable trade-offs for default behaviour, because they will generate sensible-feeling dates. However, these depend on the current time, which is constantly increasing, and will lead to subtly different outputs on each regeneration.
To deal with this, I …

feat(zod-mock): Use custom faker instance everywhere when available

---

package-lock.json
packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

If `strict` is set, then `additionalProperties` will be set to `false`.
Fixes https://github.com/anatine/zod-plugins/issues/89

feat: set additionalProperties to false if strict

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

Currently if you provide a schema with `z.string().datetime()`, the mock generated is just a standard string. 
Expectation should be that it generates a string that would pass `datetime.parse(<mock string>)` as outlined [here](https://zod.dev/?id=datetime-validation).
Side effect of this approach is obviously that any keys in the schema that map into the [`stringGenerator`](https://github.com/anatine/zod-plugins/blob/a3d40f46382f9bb29e671229c16ec7a2e9cae5de/packages/zod-mock/src/lib/zod-mock.ts#L181) will do so in an ignore case fashion (eg: all these map to the same generator: ['datetime', 'dateTime', 'DATETIME']).  Afaik this shouldn't be an issue but if it is... the issue with `z.string().datetime()` could be resolved in other ways.

[zod-mock] ensure zod.string().datetime() maps to correct string generator

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

I think this is pretty self-explanatory. `.length()` lets you provide a specific length instead of `.min().max()`, so restrain the string generation size accordingly. 🙂

feat(zod-mock): mock strings with explicit length

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

It's a simple change, but one that opens up more possibilities for people using the library. feel free to close or review. thank you for good works.
Resolve #109

feat(zod-mock): pass `zodRef` and `options` to generator function which defined in backupMocks

---

package-lock.json
package.json
packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

Hello, 
Using faker-js lib and this lib on my project, I would love to upgrade to the last version aka 8.x.x
Using the last version and zod-mock at the current version sadly create a lot of warn message.
So I decided to upgrade directly this lib with this pull request :)
Everything seems mostly fine except this test "Avoid depreciations in strings". 
I tried to get it and fix it but I am really blocking at it.
Hope it easy to fix and we can quickly move this lib to the next version of faker-js 💪

Updating faker-js lib to 8.0.x.

---

packages/zod-mock/README.md

The README had leftovers from the openapi3 package, which this PR replaces with actual instructions.

readme: Fix README.md for zod-mock

---

packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

This is useful especially for integer literals. Here's where I noticed the current behavior:
```json
"type": {
"oneOf": [
{ "type": "number", "enum": [1] },
{ "type": "number", "enum": [2] },
{ "type": "number", "enum": [3] },
{ "type": "number", "enum": [4] },
{ "type": "number", "enum": [5] },
{ "type": "number", "enum": [6] },
{ "type": "number", "enum": [7] },
{ "type": "number", "enum": [8] },
{ "type": "number", "enum": [9] },
{ "type": "number", "enum": [10] },
{ "type": "number", "enum": [11] }
]
},
```
Debatably, it might be nicer to split cases like `z.union(z.literal(4), z.literal(5), z.literal("h"), z.literal("i"))` into 2 different groups and give those to the `oneOf`, which is really not possible the way I went around this. I suspect that case is significantly rarer, …

Turn unions of literals into enums

---

package-lock.json
packages/zod-nestjs/package.json

Fixes anatine/zod-plugins#140
When using @nestjs/common 10 you need at least @nestjs/swagger 7

fix(zod-nestjs): resolve conflicting dependencies

---

package-lock.json
packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

I noticed that ZodPipeline is not currently supported.
If you have this schema for example:
```typescript
import { z } from 'zod';
import { generateSchema } from '@anatine/zod-openapi';
const schema = z
.string()
.regex(/^\d+$/)
.transform(Number)
.pipe(z.number().min(0).max(10));
const inputObjectSchema = generateSchema(schema);
// {}
const outputObjectSchema = generateSchema(schema, true);
// {}
```
After the changes of this PR:
```typescript
import { z } from 'zod';
import { generateSchema } from '@anatine/zod-openapi';
const schema = z
.string()
.regex(/^\d+$/)
.transform(Number)
.pipe(z.number().min(0).max(10));
const inputObjectSchema = generateSchema(schema);
// { type: 'string', pattern: '^\\d+$' }
const outputObjectSchema = generateSchema(schema, true);
// { type: 'number', …
```

feat: parse ZodPipeline

---

packages/zod-openapi/src/lib/zod-extensions.ts

This resolves issues when used in ESM packages. Closes #168

(zod-openapi) Fix zod deep import

---

packages/zod-mock/package.json

In using `zod-mock` with [Yarn PnP](https://yarnpkg.com/features/pnp) in a monorepo, I've found that all return types for `generateMock` are `any` because `zod` itself can't be resolved. The same problem likely exists with other package managers that use module resolution strategies other than node module resolution.
This adds `zod` as a peerDependency so types work as expected. I took the `zod` version from the top level package.json was used. Perhaps a looser specification would be appropriate.
I've confirmed this fixes the problem for Yarn PnP in my monorepo.

Add `zod` as a `peerDependency` for `zod-mock`

---

package-lock.json
package.json
packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

fixes https://github.com/anatine/zod-plugins/issues/176

[zod-openapi] bump zod to 3.22 and add support for ZodReadonly

---

packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

Overlaps with https://github.com/anatine/zod-plugins/pull/173.
fixes https://github.com/anatine/zod-plugins/issues/177

[zod-openapi] a quick take on removing "nullable" and solving nullability of `z.custom()`

---

packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

I was trying to describe some fields of the same "primitive" type that I created with zod in different places of the API, but `extendApi` was overriding the description on that type instead of changing the description for that specific use case.
A solution is to not mutate the original schema with `extendApi`.

fix(zod-openapi): do not mutate original schema with extendApi

---

packages/zod-nestjs/src/lib/create-zod-dto.spec.ts
packages/zod-nestjs/src/lib/create-zod-dto.ts

[zod-nestjs] Convert OpenAPI 3.1 to OpenAPI 3.0 for consumption by @nestjs/swagger

---

packages/zod-nestjs/src/lib/create-zod-dto.spec.ts
packages/zod-nestjs/src/lib/create-zod-dto.ts

Hi and sorry I did not fix this right away in #182.
In my project I have a somewhat advanced structure of Zod validation schemes with nested objects and arrays. So far, we only convert OpenAPI 3.1 back to OpenAPI 3.0 for objects and only on the root level, e. g. the `properties` object. However, schema objects can incorporate other schema objects in a bunch of other places, for example `anyOf` or `items` for arrays,
This PR addresses this problem by _recursively_ converting `zod-openapi`'s OpenAPI 3.1 object back to OpenAPI 3.0 for NestJS.

[zod-nestjs] Recursively convert to OpenAPI 3.0 specification

---

packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

Hi,
this PR fixes the situation when ZodPipeline has additional OpenAPI properties. Currently, they are ignored and it's impossible to add `description`  etc. to the documentation.

[zod-openapi] Merge additional OpenAPI definitions on ZodPipeline

---

packages/zod-nestjs/src/lib/create-zod-dto.spec.ts
packages/zod-nestjs/src/lib/create-zod-dto.ts

Dear Anatine Team,
I've encountered an issue where optional object fields defined with Zod are incorrectly treated as required by NestJS Swagger. Upon investigation, I discovered that NestJS Swagger defaults to marking fields as required unless explicitly stated otherwise. This behavior leads to a discrepancy when integrating Zod schemas, as fields intended to be optional are handled as required.
**Issue Example:**
Consider the following schema, where both pagination and filter are intended as optional fields:
```typescript
const schema = z.object({
pagination: z
.object({
limit: z.number(),
offset: z.number(),
})
.optional(),
filter: z
.object({
category: z.string().uuid(),
userId: z.string().uuid(),
})
.optional(),
sort: z.object({
field: z.string(),
order: z.string(),
}),
});
```
In …

 Fix Handling of Optional Zod Fields with NestJS Swagger

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

zod-mock can override string mocks with [the stringMap option](https://github.com/anatine/zod-plugins/tree/main/packages/zod-mock#overriding-string-mocks).
However, this doesn't work when the validation has regex (e.g. `z.string().regex(/^\+[1-9]\d{1,14}$/)`) since the regexCheck logic is placed before the stringMap logic.
This PR will fix the issue.

[zod-mock] Fix parseString

---

packages/zod-openapi/src/lib/zod-openapi.spec.ts
packages/zod-openapi/src/lib/zod-openapi.ts

Fixes #220 #211 #228 #212
This adds OpenAPI 3.0-specific logic so that the correct 3.0 results are generated.
Looking beyond the somewhat liberal sprinkling of 3.0-vs-3.1 conditionals, I had to add some typecasts since the base schema is incompatible in 3.0 vs 3.1 for exclusive values. I do wonder if long term, the 3.0 and 3.1 functions should be split out entirely.

Fix handling of `null`s, nullables, and exclusive{Min,Max} for OpenAPI 3.0

---

packages/zod-nestjs/src/lib/create-zod-dto.ts

fix: Improve array handling not fully functional (misses item type) #215

---

package-lock.json
package.json

Update dependencies: @faker-js/faker to 9.2.0, @anatine/graphql-codegen-zod to 0.4.1, @anatine/graphql-zod-validation to 0.9.1,

"Update dependencies: @faker-js/faker to 9.2.0

---

README.md

README used a wrong link to a different faker-lib. Now it links to the Homepage of the right project.

Update README.md, faker.js-URL

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

I noted that the mockery mapper passed in the generate mock function options is not being used exhaustively. At the moment, only faker functions that generate strings seem to be called and used. Faker functions for other primitive values are not used
This pull request addresses the issues with the mockery mapper by handling the other primitive values (date, number and boolean)
Attempts to address issue #172
The changes include:
- Support use of number faker function added to the custom mockery mapper provided
- Support use of boolean faker function added to the custom mockery mapper provided
- Support use of date faker function added to the custom mockery mapper provided
- Unit tests for the above use cases

fix(zod-mock): [#172] enhance mockeryMapper 

---

package-lock.json
packages/zod-mock/package.json

fixes #240 by adding faker 9 to the peer dependency range

fix(zod-mock): update peer dependency range for @faker-js/faker to include ^9.x

---

packages/zod-mock/src/lib/zod-mock.spec.ts
packages/zod-mock/src/lib/zod-mock.ts

This change adds support for zod readonly fields. before this change the innertype was ignored and the value was always set to undefined.
generateMock now generates the correct underlaying type.
fixes #195

feat(zod-mock): add support for readonly fields

---

packages/zod-openapi/src/lib/zod-extensions.spec.ts
packages/zod-openapi/src/lib/zod-extensions.ts
packages/zod-openapi/src/lib/zod-openapi.ts

This change allows `hideDefinition` use directly in `.openapi()` extension method.
```ts
z.object({
one: z.string(),
two: z.number()
})
.openapi({
hideDefinition: ['two']
})
```
Example above do not work right now, as `hideDefinition` is specified as an additional property on `AnatineSchemaObject`, not `SchemaObject` itself.

fix: Use AnatineSchemaObject in openapi extension method
